# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionsCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('area', models.CharField(max_length=15)),
                ('party_number', models.IntegerField()),
            ],
            options={
                'db_table': 'elections_candidate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('g_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('g_place', models.CharField(max_length=20)),
                ('g_address', models.CharField(blank=True, max_length=255, null=True)),
                ('g_call', models.CharField(blank=True, max_length=15, null=True)),
                ('g_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ground',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchmake',
            fields=[
                ('m_num', models.IntegerField(primary_key=True, serialize=False)),
                ('m_stat', models.IntegerField()),
                ('m_create_time', models.DateTimeField(blank=True, null=True)),
                ('m_money', models.IntegerField(blank=True, null=True)),
                ('m_time', models.DateTimeField(blank=True, null=True)),
                ('m_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'matchmake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('p_num', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=10)),
                ('p_age', models.IntegerField(blank=True, null=True)),
                ('p_power', models.IntegerField(blank=True, null=True)),
                ('p_position', models.CharField(blank=True, max_length=10, null=True)),
                ('p_call', models.CharField(blank=True, max_length=15, null=True)),
                ('p_pro', models.IntegerField(blank=True, null=True)),
                ('p_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=10)),
                ('t_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('t_leader', models.CharField(max_length=10)),
                ('t_call', models.CharField(max_length=15, unique=True)),
                ('t_pwd', models.IntegerField()),
                ('t_place', models.CharField(max_length=20)),
                ('t_time', models.CharField(max_length=20)),
                ('t_power', models.IntegerField()),
                ('t_point', models.FloatField(blank=True, null=True)),
                ('t_age', models.FloatField(blank=True, null=True)),
                ('t_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchwant',
            fields=[
                ('m_num', models.ForeignKey(db_column='m_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Eyedtt.Matchmake')),
                ('w_create_time', models.DateTimeField(blank=True, null=True)),
                ('w_result', models.IntegerField()),
                ('w_cancel', models.IntegerField()),
            ],
            options={
                'db_table': 'matchwant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('t_num', models.ForeignKey(db_column='t_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Eyedtt.Team')),
                ('s_day', models.IntegerField()),
                ('vii', models.IntegerField(blank=True, null=True)),
                ('viii', models.IntegerField(blank=True, null=True)),
                ('ix', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('xi', models.IntegerField(blank=True, null=True)),
                ('xii', models.IntegerField(blank=True, null=True)),
                ('xiii', models.IntegerField(blank=True, null=True)),
                ('xiv', models.IntegerField(blank=True, null=True)),
                ('xv', models.IntegerField(blank=True, null=True)),
                ('xvi', models.IntegerField(blank=True, null=True)),
                ('xvii', models.IntegerField(blank=True, null=True)),
                ('xviii', models.IntegerField(blank=True, null=True)),
                ('ixx', models.IntegerField(blank=True, null=True)),
                ('xx', models.IntegerField(blank=True, null=True)),
                ('xxi', models.IntegerField(blank=True, null=True)),
                ('xxii', models.IntegerField(blank=True, null=True)),
                ('xxiii', models.IntegerField(blank=True, null=True)),
                ('xxiv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
    ]
